### ISSUE TITLE
Stolen code straight from another package?

### ISSUE THREAD

**Issue by iDavidB** [thetayloredman/uwuify#1]
I noticed you guys stole the code from another package, why?

https://www.npmjs.com/package/uwuifier

**Comment by thetayloredman** [comment]
The code is not stolen. This was a wrapper around that library — the only “similarity” is that the assignments to faces etc look similar (but some items were removed from them, hence the reassignment and the existence of this repository)

**Comment by iDavidB** [comment]
It is literally usiong the other package and using their built-in features to assign some other faces?

**Comment by thetayloredman** [comment]
Yes. This was used in a few projects of mine to fix problems with ASCII faces and suggestive actions.

**Comment by thetayloredman** [comment]
(Before it was actually merged upstream—this project is dead.)
